**제출 시 파일 제목에 `이름`을 수정하여 제출할 것!**

# Assignment 3

**범위**

- 5 NumPy
- 6.1 Pandas_1
- 6.2 Pandas_2

In [1]:
import numpy as np
import pandas as pd

# Q.1



1. 수치형 원소로 구성된 array를 입력하였을 때 array를 `print`하고 사용자가 지정하는 기준(`threshold`) 보다 큰 원소들은 'Up', 작거나 같은 원소들은 'Down'으로 변경하는 함수인 `get_results`를 작성하시오.


In [3]:
def get_results(arr, threshold):
  print(arr)
  results = np.where(arr > threshold, 'Up', 'Down')
  return results

2. 0이상 1이하의 숫자들로 구성된 길이가 10인 array를 `np.random.uniform`을 이용하여 생성한 후, `threshold = 0.5`와 함께 `get_results` 함수에 입력한 결과를 보이시오.(seed = 123 으로 설정)

In [4]:
np.random.seed(123)
random_array = np.random.uniform(0, 1, 10)
results = get_results(random_array, threshold=0.5)
display(results)

[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897 0.42310646
 0.9807642  0.68482974 0.4809319  0.39211752]


array(['Up', 'Down', 'Down', 'Up', 'Up', 'Down', 'Up', 'Up', 'Down',
       'Down'], dtype='<U4')

# Q.2

NumPy 함수를 이용하여 1차원

*   List item
*   List item

array를 입력했을 때 원하는 방식에 따라 오름차순 정렬 또는 내림차순 정렬된 array를 출력하는 함수를 작성하고 각각의 결과를 보이시오.
```
a = np.array([4,2,3,5,1,2,0,10])
print(sorting(a, method = 'ascending))
print(sorting(a, method = 'descending'))
>>>

[ 0  1  2  2  3  4  5 10]
[10  5  4  3  2  2  1  0]

```

In [7]:
def sorting(arr, method='ascending'):
  if method == 'ascending':
    return np.sort(arr)
  elif method == 'descending':
    return np.sort(arr)[::-1]
  else:
    print("error")

a = np.array([4,2,3,5,1,2,0,10])
print(sorting(a, method = 'ascending'))
print(sorting(a, method = 'descending'))

[ 0  1  2  2  3  4  5 10]
[10  5  4  3  2  2  1  0]


# Q.3

로또 숫자 선택 및 추첨 시스템을 재현하고자 한다. 실제 로또의 규칙을 모두 재현하기는 어려우니 본 문제를 위한 규칙을 간단히 재 정리 한다.  
1) $\,\,\,$ 숫자 선택
* 한 줄(행)에 1부터 45까지의 숫자 중 서로 중복하지 않은 6개의 숫자를 고를 수 있다.
* 최대 5줄(행)까지 번호를 입력할 수 있다.

2) $\,\,\,$ 당첨 여부
* 당첨 번호는 1부터 45까지의 숫자 중 서로 중복하지 않은 6개의 숫자를 무작위로 추출한다.
* 입력한 숫자의 각 줄(행)씩 당첨 번호에 속한 숫자의 개수를 카운트 한다.  
```
ex)
입력 숫자: [[1,2,5,10,20,45],
            [2,4,5,23,28,34]]
당첨 번호: [3,5,10,24,28,40]
당첨 여부: [[False, False,  True,  True, False, False],
            [False, False,  True, False,  True, False]]
당첨 번호 개수: [2,2]
```



1. 로또 입력 번호 자동으로 생성해주는 함수 `get_auto_lotto_numbers`를 구현해본다. 함수의 입력 값은 줄의 개수이며 1줄부터 5줄까지 생성할 수 있다. 더불어, seed는 설정되어서는 안되며, 결과값으로 나오는 번호들은 각 줄(행) 마다 오름차순이어야 한다.

  ```
  ex)
  def get_auto_lotto_numbers(n:int):
    if ...:
      ...
    else:
      raise BaseException(f"줄의 개수를 다시 입력하시오!")

  lotto_numbers = get_auto_lotto_numbers(n=5)
  display(lotto_numbers)
  >>>
  array([[ 2, 11, 15, 23, 29, 45],
        [ 5, 17, 25, 31, 35, 44],
        [ 5,  8, 10, 13, 21, 25],
        [ 4,  5, 14, 21, 26, 36],
        [ 2,  7,  9, 12, 14, 17]])
  ```


In [10]:
def get_auto_lotto_numbers(n: int):
  if not 1 <= n <= 5:
    print(f"줄의 개수를 다시 입력하시오!")

  lotto_numbers = []
  for _ in range(n):
    numbers = np.random.choice(np.arange(1, 46), size=6, replace=False)
    lotto_numbers.append(np.sort(numbers))

  return np.array(lotto_numbers)

lotto_numbers = get_auto_lotto_numbers(n=5)
display(lotto_numbers)

array([[ 6, 14, 27, 37, 42, 43],
       [ 2, 19, 30, 32, 33, 39],
       [11, 16, 22, 24, 34, 40],
       [11, 14, 17, 25, 34, 37],
       [ 9, 12, 27, 31, 41, 43]])

2. 당첨번호를 생성하는 함수 `get_winning_numbers`를 구현해본다. 1부터 45까지의 숫자 중 6개를 중복없이 무작위 추출한 후 오름차순으로 정렬된 당첨번호를 생성한다. 단, seed를 입력받을 수 있도록 한다 (seed는 실제 로또의 회차 번호라고 생각하면 된다).
```
winning_numbers = get_winning_numbers(seed=1092)
display(winning_numbers)
>>>
array([ 1,  4,  8, 15, 22, 37])
```

In [12]:
import numpy as np

def get_winning_numbers(seed=None):

  if seed is not None:
    np.random.seed(seed)

  winning_numbers = np.random.choice(np.arange(1, 46), size=6, replace=False)
  return np.sort(winning_numbers)

winning_numbers = get_winning_numbers(seed=1092)
display(winning_numbers)

array([ 1,  4,  8, 15, 22, 37])

3. 1.과 2.에서 각각 생성된 입력 번호와 당첨 번호를 비교하여 결과를 알려주는 `get_lotto_results`를 구현해본다.
입력 번호와 당첨 번호를 함수의 입력값으로 설정하여 각 줄 마다 몇개의 숫자가 당첨됐는지 알려주도록 출력한다.
```
get_lotto_results(lotto_numbers,winning_numbers)
>>>
<< 당첨번호: [ 1  4  8 15 22 37] >>
1 번째 줄 당첨된 번호 개수: 0
2 번째 줄 당첨된 번호 개수: 1
3 번째 줄 당첨된 번호 개수: 0
4 번째 줄 당첨된 번호 개수: 0
5 번째 줄 당첨된 번호 개수: 0

```

In [14]:
def get_lotto_results(lotto_numbers, winning_numbers):

  print(f"<< 당첨번호: {winning_numbers} >>")
  for i, lotto_line in enumerate(lotto_numbers):
    matches = np.intersect1d(lotto_line, winning_numbers)
    print(f"{i+1} 번째 줄 당첨된 번호 개수: {len(matches)}")

get_lotto_results(lotto_numbers,winning_numbers)

<< 당첨번호: [ 1  4  8 15 22 37] >>
1 번째 줄 당첨된 번호 개수: 1
2 번째 줄 당첨된 번호 개수: 0
3 번째 줄 당첨된 번호 개수: 1
4 번째 줄 당첨된 번호 개수: 1
5 번째 줄 당첨된 번호 개수: 0


4. 다음은 로또 결과를 화면으로 확인했을 때의 모습의 예시다.  
![로또 QR코드 확인](https://blog.kakaocdn.net/dn/wCnKq/btqFvuVPxpz/wrzMfInz4wJD9eB0JeC78K/img.png)

이처럼 입력 번호 중 당첨 번호에 포함 된 것을 표시할 수 있는 함수인 `get_lotto_display_results`를 구현해본다.  
이때, 당첨 번호에 해당하는 번호는 그대로 표시하고 미당첨 번호에 해당하는 것은 'x'로 표시하도록 한다.
```
get_lotto_display_results(lotto_numbers,winning_numbers)
>>>
[['x' 'x' 'x' 'x' 'x' 'x']
 ['x' '15' 'x' 'x' 'x' 'x']
 ['x' 'x' 'x' 'x' '37' 'x']
 ['1' 'x' 'x' 'x' 'x' 'x']
 ['x' 'x' 'x' 'x' 'x' 'x']]
```

In [15]:
def get_lotto_display_results(lotto_numbers, winning_numbers):
  display_results = []
  for lotto_line in lotto_numbers:
    line_results = []
    for number in lotto_line:
      if number in winning_numbers:
        line_results.append(str(number))
      else:
        line_results.append('x')
    display_results.append(line_results)
  return np.array(display_results)

display(get_lotto_display_results(lotto_numbers,winning_numbers))

array([['x', 'x', 'x', '37', 'x', 'x'],
       ['x', 'x', 'x', 'x', 'x', 'x'],
       ['x', 'x', '22', 'x', 'x', 'x'],
       ['x', 'x', 'x', 'x', 'x', '37'],
       ['x', 'x', 'x', 'x', 'x', 'x']], dtype='<U2')

# Q.4




다음은 시험 성적이다.
```
'국어':[ 93,  82,  82,  86,  97,  99,  90,  81,  80,  97]
'영어':[ 95,  89,  80,  94,  80,  95,  99,  94,  84,  80]
'수학':[ 96,  84,  97,  83,  82, 100,  87,  82, 100,  95]
```

1. 위의 점수에 해당하는 학생들 순서는 다음과 같다: `['형원','재혁','도윤','진우','재희','상민','우준','승헌','기윤','웅찬']`  
아래의 결과를 갖는 `scores_df`라는 이름의 DataFrame을 생성하고 `display`를 이용하여 출력하시오.

	```
			국어	영어	수학
	형원	93	95	96
	재혁	82	89	84
	도윤	82	80	97
	진우	86	94	83
	재희	97	80	82
	상민	99	95	100
	우준	90	99	87
	승헌	81	94	82
	기윤	80	84	100
	웅찬	97	80	95
	```


In [16]:
import pandas as pd

scores_data = {
    '국어': [93, 82, 82, 86, 97, 99, 90, 81, 80, 97],
    '영어': [95, 89, 80, 94, 80, 95, 99, 94, 84, 80],
    '수학': [96, 84, 97, 83, 82, 100, 87, 82, 100, 95]
}

students = ['형원','재혁','도윤','진우','재희','상민','우준','승헌','기윤','웅찬']

scores_df = pd.DataFrame(scores_data, index=students)
display(scores_df)

국어  영어   수학
형원  93  95   96
재혁  82  89   84
도윤  82  80   97
진우  86  94   83
재희  97  80   82
상민  99  95  100
우준  90  99   87
승헌  81  94   82
기윤  80  84  100
웅찬  97  80   95

2. 각 학생 별로 전 과목 점수 평균을 구하는 함수를 `scores_df`에 적용하여 `평균` 이라는 이름의 열을 추가하시오. 이때, 평균은 소수점 둘째자리에서 반올림하여 첫째자리까지 나타내시오.
	```
	hint) apply, lambda x:.., np.mean, round() 를 적절히 활용하세요

	...
	display(scores_df)
	>>>  
			국어	영어	수학	평균
	형원	93	95	96	94.7
	재혁	82	89	84	85.0
	도윤	82	80	97	86.3
	진우	86	94	83	87.7
	재희	97	80	82	86.3
	상민	99	95	100	98.0
	우준	90	99	87	92.0
	승헌	81	94	82	85.7
	기윤	80	84	100	88.0
	웅찬	97	80	95	90.7
	```

In [17]:
scores_df['평균'] = scores_df.apply(lambda x: round(np.mean(x), 1), axis=1)
display(scores_df)

국어  영어   수학    평균
형원  93  95   96  94.7
재혁  82  89   84  85.0
도윤  82  80   97  86.3
진우  86  94   83  87.7
재희  97  80   82  86.3
상민  99  95  100  98.0
우준  90  99   87  92.0
승헌  81  94   82  85.7
기윤  80  84  100  88.0
웅찬  97  80   95  90.7

3. 2.에서 구한 `평균` 열을 바탕으로 학생의 등수를 나타내는 `Rank` 열을 추가하시오. 단, 등수는 정수형이다.
```
hint) rank, map 함수를 적절히 이용하시오
...
display(scores_df)
>>>
	  국어	영어	수학	평균	Rank
형원	93	95	96	94.7	2
재혁	82	89	84	85.0	10
도윤	82	80	97	86.3	7
진우	86	94	83	87.7	6
재희	97	80	82	86.3	7
상민	99	95	100	98.0	1
우준	90	99	87	92.0	3
승헌	81	94	82	85.7	9
기윤	80	84	100	88.0	5
웅찬	97	80	95	90.7	4
```

In [18]:
scores_df['Rank'] = scores_df['평균'].rank(ascending=False).astype(int)
display(scores_df)

국어  영어   수학    평균  Rank
형원  93  95   96  94.7     2
재혁  82  89   84  85.0    10
도윤  82  80   97  86.3     7
진우  86  94   83  87.7     6
재희  97  80   82  86.3     7
상민  99  95  100  98.0     1
우준  90  99   87  92.0     3
승헌  81  94   82  85.7     9
기윤  80  84  100  88.0     5
웅찬  97  80   95  90.7     4

4. `Rank`열만 이용하여 1등부터 10등까지 내림차순으로 index(이름)와 등수가 정렬된 `Series`의 모습을 `display`를 이용하여 출력하시오.


In [19]:
rank_series = scores_df['Rank'].sort_values(ascending=True)
display(rank_series)

상민     1
형원     2
우준     3
웅찬     4
기윤     5
진우     6
재희     7
도윤     7
승헌     9
재혁    10
Name: Rank, dtype: int64

# Q.5

nested dictionary를 이용하여 다음의 데이터 프레임을 생성하시오. 이때, 가장 좌측에 '이름'아래에 있는 값들은 index로 설정한다.
```
display(dataframe)
>>>
	              국적	소속팀	득점
이름
킬리안 음바페	프랑스	파리 생제르맹	10
엘링 홀란	    노르웨이	맨시티	     11
손흥민	      대한민국	 토트넘	     8
모하메드 살라	이집트	  리버풀	     8
황희찬	      대한민국	울버햄튼	    6
주드 벨링엄	잉글랜드	레알 마드리드	10
해리 케인	  잉글랜드	바이에른 뮌헨	15
```

In [1]:
import pandas as pd

player_data = {
    '국적': {'킬리안 음바페': '프랑스', '엘링 홀란': '노르웨이', '손흥민': '대한민국', '모하메드 살라': '이집트', '황희찬': '대한민국', '주드 벨링엄': '잉글랜드', '해리 케인': '잉글랜드'},
    '소속팀': {'킬리안 음바페': '파리 생제르맹', '엘링 홀란': '맨시티', '손흥민': '토트넘', '모하메드 살라': '리버풀', '황희찬': '울버햄튼', '주드 벨링엄': '레알 마드리드', '해리 케인': '바이에른 뮌헨'},
    '득점': {'킬리안 음바페': 10, '엘링 홀란': 11, '손흥민': 8, '모하메드 살라': 8, '황희찬': 6, '주드 벨링엄': 10, '해리 케인': 15}
}

dataframe = pd.DataFrame(player_data)
dataframe.index.name = '이름'
display(dataframe)

국적      소속팀  득점
이름                        
킬리안 음바페   프랑스  파리 생제르맹  10
엘링 홀란    노르웨이      맨시티  11
손흥민      대한민국      토트넘   8
모하메드 살라   이집트      리버풀   8
황희찬      대한민국     울버햄튼   6
주드 벨링엄   잉글랜드  레알 마드리드  10
해리 케인    잉글랜드  바이에른 뮌헨  15

# Q.6

`Personal Loan.csv`는 개인 별 기본 인적사항과 함께 대출의 여부가 담긴 데이터셋 파일이다. [[출처: Kaggle]](https://www.kaggle.com/datasets/teertha/personal-loan-modeling)

1. `pd.read_csv()`를 이용해 데이터를 불러와 `loan_df`라는 이름으로 `DataFrame`을 정의하고, `Personal Loan` 열이 개인 대출 여부를 나타낼 때 (1: 대출 , 0: 미대출), 대출한 인원과 대출하지 않은 인원이 각각 몇 명인지 확인하시오.


In [4]:
loan_df = pd.read_csv('/content/PersonalLoan.csv')

loan_counts = loan_df['Personal Loan'].value_counts()

print("대출 여부에 따른 인원 수:")
print(f"대출 (1): {loan_counts.get(1, 0)} 명")
print(f"미대출 (0): {loan_counts.get(0, 0)} 명")

대출 여부에 따른 인원 수:
대출 (1): 256 명
미대출 (0): 2244 명


2. `Education`은 각 인원의 교육 수준( 1: 대학 졸업, 2: 대학원 졸업, 3: 전문가)을 나타낸 것이다. 이때, 대출여부에 따른 교육수준 별 인원이 각각 몇명인지 확인하시오.


In [5]:
education_loan_counts = loan_df.groupby('Personal Loan')['Education'].value_counts().unstack(fill_value=0)

print("대출 여부에 따른 교육 수준별 인원 수:")
print(education_loan_counts)

대출 여부에 따른 교육 수준별 인원 수:
Education         1    2    3
Personal Loan                
0              1013  605  626
1                52  101  103


3. 대출여부 별 나이(Age)와 수입(Income)의 평균(소수점 둘째 자리에서 반올림)을 하나의 데이터프레임 형태로 나타내시오.

In [7]:
average_age_income = loan_df.groupby('Personal Loan')[['Age', 'Income']].mean().round(2)

print("대출 여부 별 나이와 수입 평균:")
display(average_age_income)

대출 여부 별 나이와 수입 평균:


Age  Income
Personal Loan               
0              45.36   66.30
1              45.25  145.91

# Q.7

다음은 우리나라 남자 축구국가대표팀 선수 별 MBTI 검사 결과다.(실제와 다를 수 있음)  
```
	    E/I	S/N	F/T	J/P
조규성	37	12	72	9
황희찬	75	5	79	64
손흥민	16	1	76	71
이강인	6	25	50	20
백승호	18	84	11	28
황인범	29	14	50	68
설영우	87	87	94	96
김민재	86	13	9	7
김영권	63	61	22	57
김태환	1	0	60	81
김승규	8	88	13	47
```
MBTI 결과지를 해석하는 방법은 다음과 같다.
* A/B : 50점 이상 = A, 50점 미만 = B  
	* ex)
	E/I : 50점 이상 =  E | 50점 미만 = I  

위와 같은 MBTI 결과의 데이터프레임을 입력하면 아래와 같은 결과의 데이터프레임을 출력하는 함수 `get_MBTI`를 작성한 후 출력 값을 보이시오.

```
get_MBTI(mbti_results)
>>>
	      MBTI
김민재	ENTP
김승규	ISTP
김영권	ESTJ
김태환	INFJ
백승호	ISTP
설영우	ESFJ
손흥민	INFJ
이강인	INFP
조규성	INFP
황인범	INFJ
황희찬	ENFJ
```

hint 1
```
mbti_results_dict =  {
                      'E/I': {'조규성': 37, '황희찬': 75, '손흥민': 16, '이강인': 6, '백승호': 18, '황인범': 29, '설영우': 87, '김민재': 86, '김영권': 63, '김태환': 1, '김승규': 8},
                      'S/N': {'조규성': 12, '황희찬': 5, '손흥민': 1, '이강인': 25, '백승호': 84, '황인범': 14, '설영우': 87, '김민재': 13, '김영권': 61, '김태환': 0, '김승규': 88},
                      'F/T': {'조규성': 72, '황희찬': 79, '손흥민': 76, '이강인': 50, '백승호': 11, '황인범': 50, '설영우': 94, '김민재': 9, '김영권': 22, '김태환': 60, '김승규': 13},
                      'J/P': {'조규성': 9, '황희찬': 64, '손흥민': 71, '이강인': 20, '백승호': 28, '황인범': 68, '설영우': 96, '김민재': 7, '김영권': 57, '김태환': 81, '김승규': 47}
                      }
```

hint2
```
def get_MBTI(df):
  result_dict = {name:... for name in ...}
  for col in ...:
    results = np.where(...)
    for name, result in zip(...,results):
      ...
  
  mbti_dict = {'MBTI':{...}}

  return pd.DataFrame(mbti_dict)
```

In [9]:
mbti_results_dict = {
    'E/I': {'조규성': 37, '황희찬': 75, '손흥민': 16, '이강인': 6, '백승호': 18, '황인범': 29, '설영우': 87, '김민재': 86, '김영권': 63, '김태환': 1, '김승규': 8},
    'S/N': {'조규성': 12, '황희찬': 5, '손흥민': 1, '이강인': 25, '백승호': 84, '황인범': 14, '설영우': 87, '김민재': 13, '김영권': 61, '김태환': 0, '김승규': 88},
    'F/T': {'조규성': 72, '황희찬': 79, '손흥민': 76, '이강인': 50, '백승호': 11, '황인범': 50, '설영우': 94, '김민재': 9, '김영권': 22, '김태환': 60, '김승규': 13},
    'J/P': {'조규성': 9, '황희찬': 64, '손흥민': 71, '이강인': 20, '백승호': 28, '황인범': 68, '설영우': 96, '김민재': 7, '김영권': 57, '김태환': 81, '김승규': 47}
}

mbti_results_df = pd.DataFrame(mbti_results_dict)

def get_MBTI(df):
  mbti_mapping = {
      'E/I': {True: 'E', False: 'I'},
      'S/N': {True: 'S', False: 'N'},
      'F/T': {True: 'F', False: 'T'},
      'J/P': {True: 'J', False: 'P'}
  }

  mbti_dict = {'MBTI': {}}
  for index, row in df.iterrows():
    mbti = ""
    for col in df.columns:
      is_greater_than_50 = row[col] >= 50
      mbti += mbti_mapping[col][is_greater_than_50]
    mbti_dict['MBTI'][index] = mbti

  return pd.DataFrame(mbti_dict)

display(get_MBTI(mbti_results_df))

MBTI
조규성  INFP
황희찬  ENFJ
손흥민  INFJ
이강인  INFP
백승호  ISTP
황인범  INFJ
설영우  ESFJ
김민재  ENTP
김영권  ESTJ
김태환  INFJ
김승규  ISTP

# Q.8

다음은 타이타닉호 침몰 당시 승객들의 정보가 담긴 데이터셋 (titanic1.csv, titanic2.csv)을 활용한다. [[출처:kaggle]](https://www.kaggle.com/competitions/titanic/overview)

1. 'titanic1.csv', 'titanic2.csv' 파일을 `encoding`을 'utf-8'로 설정하여 읽어 각각 `titanic1, titanic2`라는 이름으로 정의한다. `titanic1`과 `titanic2`는 모두 `ID` 열을 포함하고 있다. `ID`를 key로 지정하고, key 의 값이 동일한 샘플들만 가지고 병합한 데이터프레임을 `merged_df` 라는 이름으로 정의하고, 처음 10개의 샘플을 보이시오.

In [11]:

titanic1 = pd.read_csv('titanic1.csv', encoding='utf-8')
titanic2 = pd.read_csv('titanic2.csv', encoding='utf-8')

merged_df = pd.merge(titanic1, titanic2, on='ID')
display(merged_df.head(10))

ID  survived     fare   age alive  parch  adult_male  gender  pclass  \
0   82         0   7.8958  28.0    no      0        True    male       3   
1  181         0   9.3500  22.0    no      0        True    male       3   
2  195         0   7.1250  22.0    no      0        True    male       3   
3  486         0  16.1000  26.0    no      0       False  female       3   
4  231         0   7.8958  22.0    no      0        True    male       3   
5   81         0   7.9250  37.0    no      0        True    male       3   
6  210         1  31.3875   3.0   yes      2       False    male       3   
7  572         1  33.0000   6.0   yes      1       False  female       2   
8   49         1  10.5000  29.0   yes      0       False  female       2   
9  230         1   9.5000  30.0   yes      0        True    male       3   

   sibsp embarked   class     who  embark_town  
0      0        S   Third    male  Southampton  
1      0        S   Third    male  Southampton  
2      0        S   Third    male  Southampton  
3      1        S   Third  female  Southampton  
4      0        S   Third    male  Southampton  
5      2        S   Third    male  Southampton  
6      4        S   Third   child  Southampton  
7      0        S  Second   child  Southampton  
8      0        S  Second  female  Southampton  
9      0        S   Third    male  Southampton

2. `parch`는 동반 승선한 부모님 또는 자식의 수이며 `sibsp`는 동반 승선한 배우자 또는 형제/자매의 수를 나타낸다. 이에, `parch`와 `sibsp` `display`를 이용해 각 승객의 동반자가 있는지 없는 지 여부를 판단하는 열인 `alone`을 `merged_df`에 추가한 후 `merged_df`의 처음 10개의 샘플을 보이시오.


In [12]:
merged_df['alone'] = (merged_df['parch'] == 0) & (merged_df['sibsp'] == 0)
display(merged_df.head(10))

ID  survived     fare   age alive  parch  adult_male  gender  pclass  \
0   82         0   7.8958  28.0    no      0        True    male       3   
1  181         0   9.3500  22.0    no      0        True    male       3   
2  195         0   7.1250  22.0    no      0        True    male       3   
3  486         0  16.1000  26.0    no      0       False  female       3   
4  231         0   7.8958  22.0    no      0        True    male       3   
5   81         0   7.9250  37.0    no      0        True    male       3   
6  210         1  31.3875   3.0   yes      2       False    male       3   
7  572         1  33.0000   6.0   yes      1       False  female       2   
8   49         1  10.5000  29.0   yes      0       False  female       2   
9  230         1   9.5000  30.0   yes      0        True    male       3   

   sibsp embarked   class     who  embark_town  alone  
0      0        S   Third    male  Southampton   True  
1      0        S   Third    male  Southampton   True  
2      0        S   Third    male  Southampton   True  
3      1        S   Third  female  Southampton  False  
4      0        S   Third    male  Southampton   True  
5      2        S   Third    male  Southampton  False  
6      4        S   Third   child  Southampton  False  
7      0        S  Second   child  Southampton  False  
8      0        S  Second  female  Southampton   True  
9      0        S   Third    male  Southampton   True

3. `class` 열은 각 승객의 좌석 등급을 나타낸다. 지금까지 배운 내용을 바탕으로 앞서 정의한 `merged_df`를 이용하여 다음의 결과를 같는 `survived_class_df`를 생성하시오.
```
counts_df = ...
survived_class_df = counts_df...
survived_class_df['Total'] = ...
survived_class_df.columns.name = None
display(survived_class_df)
>>>
	First	Second	Third	Total
survived
0	7	18	45	70
1	29	12	16	57
```

In [13]:
counts_df = merged_df.groupby('survived')['class'].value_counts().unstack(fill_value=0)
survived_class_df = counts_df[['First', 'Second', 'Third']]
survived_class_df['Total'] = survived_class_df.sum(axis=1)
survived_class_df.columns.name = None
display(survived_class_df)

First  Second  Third  Total
survived                             
0             7      18     45     70
1            29      12     16     57

# Q.9

`NikeDraw.csv` 파일은 나이키 덩크 로우 Black and Gum Light Brown 응모 접수 데이터다.  


1. 응모 규칙은 다음과 같다.  
* 이메일 주소, 사이즈, 응모 지점 중 하나라도 공백이 있는 행은 제거한다.
* 하나의 이메일 주소 당 최대 두 개의 응모 지점에 응모할 수 있다.
* 만약, 하나의 이메일 주소로 3개 이상의 응모 지점에 응모하였을 경우, 처음 2개의 응모 내역만 인정한다.
* 중복된 내역은 마지막 하나만 남겨두고 다 제거한다.  

위의 규칙으로 응모 접수 데이터를 전처리하는 함수 `preprocess`를 생성하고 실제 결과를 출력하시오.(`NikeDraw.csv` 파일의 encoding은 'cp949'로 설정하여야 함)

```
data_df = ...
final_df = preprocess(data_df)
display(final_df)
>>>

                  이메일	사이즈	응모지점
0	doyooni303@korea.ac.kr	265.0	목동점
1	gunho_no@korea.ac.kr	270.0	목동점
2	jinwoo_park@korea.ac.kr	260.0	안암점
3	joonghoon_kim@korea.ac.kr	280.0	용인점
4	seonghee_hong@korea.ac.kr	275.0	포항점
6	sangmin_lee@korea.ac.kr	270.0	안암점
7	woojun_lee@korea.ac.kr	275.0	여의도점
8	jiyoon_lee@korea.ac.kr	230.0	덕소점
11	woongchan_nam@korea.ac.kr	270.0	영등포점
13	seonghee_hong@korea.ac.kr	275.0	영등포점
14	gunho_no@korea.ac.kr	270.0	안암점

```

In [16]:
import pandas as pd

def preprocess(df):

  df.dropna(subset=['이메일', '사이즈', '응모지점'], inplace=True)

  df = df.groupby('이메일').head(2).reset_index(drop=True)

  df.drop_duplicates(subset=['이메일', '사이즈', '응모지점'], keep='last', inplace=True)

  return df

data_df = pd.read_csv('NikeDraw.csv', encoding='cp949')
final_df = preprocess(data_df)
display(final_df)

이메일    사이즈  응모지점
0      doyooni303@korea.ac.kr  265.0   목동점
1        gunho_no@korea.ac.kr  270.0   목동점
2     jinwoo_park@korea.ac.kr  260.0   안암점
3   joonghoon_kim@korea.ac.kr  280.0   용인점
4   seonghee_hong@korea.ac.kr  275.0   포항점
5     sangmin_lee@korea.ac.kr  270.0   안암점
6      woojun_lee@korea.ac.kr  275.0  여의도점
7      jiyoon_lee@korea.ac.kr  230.0   덕소점
8   woongchan_nam@korea.ac.kr  270.0  영등포점
9   seonghee_hong@korea.ac.kr  275.0  영등포점
10       gunho_no@korea.ac.kr  270.0   안암점

2. 1에서 전처리 완료된 최종 응모 내역 데이터 `final_df`에서 50%가 무작위로 당첨된다고 하자. 이를 구현하는 함수 `get_results`를 생성하고 `final_df`를 입력한 결과를 출력하시오.

  * 50%의 의미: 최종 응모내역 10건 → 5건 당첨 / 최종 응모내역 11건 → 5건 당첨
  * seed나 random_state는 별도로 지정하지 않음

    ```
    ex)
    get_results(final_df)
    >>>
              이메일	사이즈	응모지점
    14	gunho_no@korea.ac.kr	270.0	안암점
    0	doyooni303@korea.ac.kr	265.0	목동점
    1	gunho_no@korea.ac.kr	270.0	목동점
    13	seonghee_hong@korea.ac.kr	275.0	영등포점
    6	sangmin_lee@korea.ac.kr	270.0	안암점
    ```


In [18]:
def get_results(df):

  num_winners = int(len(df) * 0.5)
  winners_df = df.sample(n=num_winners, replace=False)
  return winners_df

winning_entries = get_results(final_df)
display(winning_entries)

이메일    사이즈  응모지점
3  joonghoon_kim@korea.ac.kr  280.0   용인점
6     woojun_lee@korea.ac.kr  275.0  여의도점
9  seonghee_hong@korea.ac.kr  275.0  영등포점
1       gunho_no@korea.ac.kr  270.0   목동점
7     jiyoon_lee@korea.ac.kr  230.0   덕소점